### ISSUE TITLE
file-drag-handle do not work on chrome 62

### ISSUE THREAD

**Issue by 33kuai** [kartik-v/yii2-widget-fileinput#123]
file-drag-handle do not work on chrome 62？  but work on other chrome version。Anyone meet the same thing？

**Comment by morawskim** [comment]
I have the same issue. On Chrome 62, file sorting is not working.
I check the source code of "kartik-v/bootstrap-fileinput" at version 4.4.6.
I notice that this library use "Sortable" library from RubaXa at version 1.5.1 with small modifications (https://github.com/RubaXa/Sortable).

I check their online demo (http://rubaxa.github.io/Sortable/). The demo works in chrome 62.

I downloaded thier source code and checked which commit fix issue with chrome 62. After some `git biselect`, I got a commit (https://github.com/RubaXa/Sortable/commit/f096574f54e82d34a3c6fa97e521cf71fb189299):
```
commit f096574f54e82d34a3c6fa97e521cf71fb189299
Author: 진유정 <you11036@gmail.com>
Date:   Wed May 31 00:14:41 2017 +0900

    fix #1071
    
    - off pointercancel event

```
If you manually change file "vendor/kartik-v/bootstrap-fileinput/js/plugins/sortable.js", sorting on chrome 62 should works.


I will investigate whether "Sortable.js" at version 1.7 works on Firefox 52. Because I have some problems. I will check other browsers, too.
If it will work I update file "vendor/kartik-v/bootstrap-fileinput/js/plugins/sortable.js" to version 1.7.0 and send a patch.

**Comment by morawskim** [comment]
I create a fork of "kartik-v/bootstrap-fileinput".
If you want, you can add to your composer.json repository:
```json
...
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/morawskim/bootstrap-fileinput"
        }
    ]
```

And to your require:
```json
"kartik-v/bootstrap-fileinput": "dev-chrome62 as 4.4.x-dev"
```
After install/update you should use kartik-v/bootstrap-fileinput from my fork.
``` bash
composer show | grep kartik-v/bootstrap-fileinput
kartik-v/bootstrap-fileinput   dev-chrome62 f78df0e An enhanced HTML 5 ...
```

**Comment by kartik-v** [comment]
@morawskim  - can you please submit a Pull request to the bootstrap-fileinput repo please? Thanks.

**Comment by morawskim** [comment]
@kartik-v Done. I created pull request.

**Comment by ElijahKaftanov** [comment]
@kartik-v Can you please release new version with this fix?
