### ISSUE TITLE
Append another file instead of replace

### ISSUE THREAD

**Issue by fabiomlferreira** [kartik-v/yii2-widget-fileinput#144]
When we are using this plugin and we enable multiple files support if we add one file and then we try to add another instead of append it will replace the first file.

This is annoying in many cases, imagine that you have multiple files to upload in different folders you can drag some file from one folder then go to other folder and drag other files but at the moment the last ones will replace the others.

I saw that if we use ajax upload the plugin works as expected but if we use the classic way the plugin replace instead of append new files. Any solution?

**Comment by kartik-v** [comment]
There are limitations in the Form Based submission mode (as the functionality is limited by to what the NATIVE HTML file input supports). 

You may [want to go through the plugin documentation to understand the comparison of the form based and ajax based modes](http://plugins.krajee.com/file-input#usage-modes) and see what is possible and what is not possible.

The ajax mode of upload supports wider options because the plugin is able to tweak and add the functionality via javascript - while for native html file input based form submission some of these are not possible.
